config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get 'home/index'
  
  devise_for :users
  resources :medicamentos
  root "home#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cupom.rb
class Cupom < ApplicationRecord
  belongs_to :medicamento
end

app/models/medicamento.rb
class Medicamento < ApplicationRecord
	def self.search(search)
		if search
			where(["nome LIKE ?","%#{search}%"])
		else
			all
		end
	end

	has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }
        validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
	has_many :cupoms
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/medicamentos_controller.rb
class MedicamentosController < ApplicationController
  before_action :authenticate_user!, only: [:create, :show, :edit, :update, :destroy, :new]
  before_action :set_medicamento, only: [:show, :edit, :update, :destroy]

  # GET /medicamentos
  # GET /medicamentos.json
  def index
    @medicamentos = Medicamento.search(params[:search])
    #@medicamentos = Medicamento.all
  end

  # GET /medicamentos/1
  # GET /medicamentos/1.json
  def show
  end

  # GET /medicamentos/new
  def new
    @medicamento = Medicamento.new
  end

  # GET /medicamentos/1/edit
  def edit
  end

  # POST /medicamentos
  # POST /medicamentos.json
  def create
    @medicamento = Medicamento.new(medicamento_params)

    respond_to do |format|
      if @medicamento.save
        format.html { redirect_to @medicamento, notice: 'Medicamento was successfully created.' }
        format.json { render :show, status: :created, location: @medicamento }
      else
        format.html { render :new }
        format.json { render json: @medicamento.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /medicamentos/1
  # PATCH/PUT /medicamentos/1.json
  def update
    respond_to do |format|
      if @medicamento.update(medicamento_params)
        format.html { redirect_to @medicamento, notice: 'Medicamento was successfully updated.' }
        format.json { render :show, status: :ok, location: @medicamento }
      else
        format.html { render :edit }
        format.json { render json: @medicamento.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /medicamentos/1
  # DELETE /medicamentos/1.json
  def destroy
    @medicamento.destroy
    respond_to do |format|
      format.html { redirect_to medicamentos_url, notice: 'Medicamento was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_medicamento
      @medicamento = Medicamento.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def medicamento_params
      params.require(:medicamento).permit(:nome, :preco_inicial, :preco_final, :validade, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/medicamentos_helper.rb
module MedicamentosHelper
end

app/views/home/index.html.erb
<section id="viability">
                <div class="container">
                    <div class="card">
                        <div class="card-icon pills"></div>
                        <div class="card-text">
                            <span>Evite o desperdício</span>
                            <p>Em 201X, Y medicamentos foram incinerados
                            pela perda da validade, ocasionando Z% do gás
                            carbono liberado na atmosfera no mesmo ano</p>
                        </div>
                    </div>
                    <div class="card">
                        <div class="card-icon plus"></div>
                        <div class="card-text">
                            <span>Responsabilidade ambiental</span>
                            <p>Ao adquirir um produto, você estará
                            evitando o desperdício de medicamentos e que
                            mais gases poluentes sejam emitidos</p>
                        </div>
                    </div>
                </div>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta charset="UTF-8"> 
    <link rel="stylesheet" href="style.css" type="text/css" />
    
  </head>

  <body>
  	<div class="wrapper">
            
            <div id="hero">
                <h1>Compre remédios com desconto</h1>
                <h3>Encontre medicamentos com até 90% de desconto</h3>
                <a href="#" id="hero-button">Pesquisar</a>
                <a><%= form_tag medicamentos_path, :method => 'get' do %>
                    <%= text_field_tag :search, params[:search] %>
                    <%= submit_tag "Pesquisar" %>
                <% end %>
                </a>
            </div>
            
            <nav>
                <span class="green-logo">mediz.in</span>
                <ul>
                    <li><a href="/medicamentos">Descontos</a></li>
                    <li><a href="#">Comprimissos</a></li>
                </ul>
            </nav>
            
            
            
    </div>
    <%= yield %>
  </body>
  <% if current_user %>
    <%= link_to "Logout", destroy_user_session_path, method: :delete %>
  <% else %>
    <%= link_to "Login", new_user_session_path %>
  <% end %>
</html>

app/views/medicamentos/_form.html.erb
<%= form_with(model: medicamento, multipart: true) do |form| %>
  <% if medicamento.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(medicamento.errors.count, "error") %> prohibited this medicamento from being saved:</h2>

      <ul>
      <% medicamento.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
    <%= form.label :image %>
    <%= form.file_field :image %>
  </div>

  <div class="field">
    <%= form.label :nome %>
    <%= form.text_field :nome, id: :medicamento_nome %>
  </div>

  <div class="field">
    <%= form.label :preco_inicial %>
    <%= form.text_field :preco_inicial, id: :medicamento_preco_inicial %>
  </div>

  <div class="field">
    <%= form.label :preco_final %>
    <%= form.text_field :preco_final, id: :medicamento_preco_final %>
  </div>

  <div class="field">
    <%= form.label :validade %>
    <%= form.text_field :validade, id: :medicamento_validade %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/medicamentos/edit.html.erb
<h1>Editing Medicamento</h1>

<%= render 'form', medicamento: @medicamento %>

<%= link_to 'Show', @medicamento %> |
<%= link_to 'Back', medicamentos_path %>

app/views/medicamentos/index.html.erb
<p id="notice"><%= notice %></p>

<section id="discounts">
  <div class="container">
    <div id="discounts-grid">
      <% @medicamentos.each do |medicamento| %>
        <div class="discount-card">
          <%= image_tag medicamento.image.url(:thumb) %>
          <span><%= medicamento.nome %></span>
          <div class="card-preco">de R$ <span class="strike"><%= medicamento.preco_inicial %></span><br>
            por R$ <%= medicamento.preco_final %>
            <br>
            desconto de X%!
          </div>
          <span></span>
          <span>Validade: <%= medicamento.validade %></span>
        </div>
      <%end%>
    </div>
  </div>
</section>


<!-- <table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>De</th>
      <th>Por</th>
      <th>Validade</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @medicamentos.each do |medicamento| %>
      <tr>
        <td><%= medicamento.nome %></td>
        <td><%= medicamento.preco_inicial %></td>
        <td><%= medicamento.preco_final %></td>
        <td><%= medicamento.validade %></td>
        <td><%= link_to 'Show', medicamento %></td>
        <td><%= link_to 'Edit', edit_medicamento_path(medicamento) %></td>
        <td><%= link_to 'Destroy', medicamento, method: :delete, data: { confirm: 'Tem certeza?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Novo Medicamento', new_medicamento_path %> -->

app/views/medicamentos/new.html.erb
<h1>New Medicamento</h1>

<%= render 'form', medicamento: @medicamento %>

<%= link_to 'Back', medicamentos_path %>

app/views/medicamentos/show.html.erb
<p id="notice"><%= notice %></p>


<%= image_tag @medicamento.image.url(:thumb) %>
<p>
  <strong>Nome:</strong>
  <%= @medicamento.nome %>
</p>

<p>
  <strong>Preco inicial:</strong>
  <%= @medicamento.preco_inicial %>
</p>

<p>
  <strong>Preco final:</strong>
  <%= @medicamento.preco_final %>
</p>

<p>
  <strong>Validade:</strong>
  <%= @medicamento.validade %>
</p>

<%= link_to 'Edit', edit_medicamento_path(@medicamento) %> |
<%= link_to 'Back', medicamentos_path %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>